server:
  port: 8123

  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000

spring:
  profiles:
    active: local
  #指定上传体积
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB  # 建议添加整个请求的大小限制

  application:
    name: ph-picture-back

  session:
    store-type: redis
    timeout: 2592000

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ph_picture
    username: ${phoj.datasource.username}
    password: ${phoj.datasource.password}

  redis:
    host: localhost
    port: 6379
    database: 0

  minio:
    access-key: ${phoj.minio.accessKey}
    secret-key: ${phoj.minio.secretKey}
    url: http://127.0.0.1:9005
    bucket-name: phpicture
  rabbitmq:
    host: localhost
    port: 5672
    password: ${phoj.rabbitmq.password}
    username: ${phoj.rabbitmq.username}
  mail:
    port: 465 # QQ邮箱端口号
    default-encoding: UTF-8 # 默认编码
    host: smtp.qq.com # QQ邮箱的SMTP服务器地址
    username: ${phoj.mail.username} # QQ邮箱账号
    password: ${phoj.mail.password} # QQ邮箱授权码
    properties:
      mail:
        smtp:
          auth: true # 是否需要认证
          ssl:
            enable: true # 是否启用ssl
            requried: true # 是否需要ssl
            protocol: TLSv1.2 # 协议
          debug: true # 是否开启调试模式

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    #    仅在开发环境中使用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.ph.phpictureback.controller


cos:
  client:
    host: ${phoj.client.host}
    SecretId: ${phoj.client.SecretId}
    SecretKey: ${phoj.client.SecretKey}
    region: ${phoj.client.region}
    bucket: ${phoj.client.bucket}


aliyun:
  apiKey: ${phoj.aliyun.apiKey}


xun-fei:
  client:
    appId: ${phoj.xunfei.appId}
    apiSecret: ${phoj.xunfei.apiSecret}
    apiKey: ${phoj.xunfei.apiKey}
